CREATE TABLE [EXCEL] (
	[DataEntrega]		DATETIME		NOT NULL,
	[NomeProduto]		VARCHAR(50)		NOT NULL,
	[Quantidade]		INT				NOT NULL,
	[ValorUnitario]		DECIMAL(18,2)	NOT NULL,
	[Id]				INT				NOT NULL,
	CONSTRAINT [FK_EXCEL_IMPORTACAO_EXCEL] FOREIGN KEY ([Id]) REFERENCES [dbo].[IMPORTACAO_EXCEL] ([Id])
)

CREATE NONCLUSTERED INDEX [IDX_EXCEL] ON [dbo].[EXCEL]
(
	[Id]
) WITH (
	PAD_INDEX = OFF,
	STATISTICS_NORECOMPUTE = OFF,
	SORT_IN_TEMPDB = OFF,
	DROP_EXISTING = OFF,
	ONLINE = OFF,
	ALLOW_ROW_LOCKS = ON,
	ALLOW_PAGE_LOCKS = ON
) ON [PRIMARY]