CREATE TABLE [IMPORTACAO_EXCEL] (
	[Id]				INT				IDENTITY(1,1),
	[NomeArquivo]		VARCHAR(100)	NOT NULL,
	[DataImportacao]	DATETIME		NOT NULL,
	CONSTRAINT [PK_IMPORTACAO_EXCEL] PRIMARY KEY ([Id]),
)

CREATE NONCLUSTERED INDEX [IDX_IMPORTACAO_EXCEL] ON [dbo].[IMPORTACAO_EXCEL]
(
	[Id]
) WITH (
	PAD_INDEX = OFF,
	STATISTICS_NORECOMPUTE = OFF,
	SORT_IN_TEMPDB = OFF,
	DROP_EXISTING = OFF,
	ONLINE = OFF,
	ALLOW_ROW_LOCKS = ON,
	ALLOW_PAGE_LOCKS = ON
) ON [PRIMARY]